name: Snyk security test CI

on:
  workflow_run:
    workflows: ["master"]
    types:
      - completed

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: use node.js
              uses: actions/setup-node@v2
              with:
                node-version: 14.x

            - name: Install snyk
              run: npm install -g snyk
            - name: authenticate snyk
              run: snyk auth ${{ secrets.SNYK_TOKEN }}

            - name: check npm files
              id: check_files_npm
              uses: andstor/file-existence-action@v1
              with:
                files: "package.json, package-lock.json"

            - name: npm snyk test
              run: snyk test -d || true

            - name: check yarn files
              if: steps.check_files_npm.outputs.files_exists != 'true'
              id: check_files_yarn
              uses: andstor/file-existence-action@v1
              with:
                files: "package.json, yarn.lock"

            - name: yarn snyk test
              if: steps.check_files_yarn.outputs.files_exists == 'true'
              run: snyk test -d || true

            - name: check no lock file
              if: steps.check_files_yarn.outputs.files_exists != 'true'
              id: check_files
              uses: andstor/file-existence-action@v1
              with:
                files: "package.json"

            - name: install and snyk test
              if: steps.check_files.outputs.files_exists == 'true'
              run: npm install
            - name: snyk test
              run: snyk test -d || true
