name: OWASP ZAP Authenticated Scan - Juice Shop

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: read    
  issues: write    
  security-events: write  
  actions: read  

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull OWASP ZAP Docker Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Inject Secrets into Context File
        run: |
          sed -i "s/REPLACE_WITH_USERNAME/${{ secrets.ZAP_AUTH_USERNAME }}/g" .zap/juice-shop-context.json
          sed -i "s/REPLACE_WITH_PASSWORD/${{ secrets.ZAP_AUTH_PASSWORD }}/g" .zap/juice-shop-context.json

      - name: Debug Context File (Optional)
        run: cat .zap/juice-shop-context.json

      - name: Run ZAP Full Scan with Authentication
        run: |
          docker run --rm \
            -v $(pwd):/zap/wrk:rw \
            --network=host \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t ${{ secrets.ZAP_TARGET_URL }} \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            -n .zap/juice-shop-context.json \
            -U ${{ secrets.ZAP_AUTH_USERNAME }} \
            -z "
                -config api.key=${{ secrets.ZAP_API_KEY }} 
                -config auth.method=manual 
                -config auth.username=${{ secrets.ZAP_AUTH_USERNAME }} 
                -config auth.password=${{ secrets.ZAP_AUTH_PASSWORD }}
            "

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_json.json
            report_md.md
            report_html.html
