name: OWASP ZAP Authenticated Scan - Juice Shop

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger
permissions:
  contents: read    
  issues: write    
  security-events: write  
  actions: read  

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OWASP ZAP
        run: |
          mkdir -p /zap
          cd /zap
          wget -N https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
          tar -zxvf ZAP_2.9.0_Linux.tar.gz
          rm ZAP_2.9.0_Linux.tar.gz
          echo 'export PATH_ZAP_SH=/zap/ZAP_2.9.0/zap.sh' >> ~/.bashrc
          echo 'export ZAP_PORT=8090' >> ~/.bashrc
          source ~/.bashrc

      - name: Copy ZAP Context File
        run: |
          mkdir -p /zap/wrk
          cp .zap/juice-shop-context.json /zap/wrk/juice-shop-context.json

      - name: Start ZAP Daemon
        run: |
          /zap/ZAP_2.9.0/zap.sh -daemon -host 0.0.0.0 -port 8090 \
          -config api.key=${{ secrets.ZAP_API_KEY }} \
          -config context.file=/zap/wrk/juice-shop-context.json > /dev/null &

      - name: Wait for ZAP to Start
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Run ZAP Full Scan
        run: |
          /zap/ZAP_2.9.0/zap.sh -cmd -quickurl=${{ secrets.ZAP_TARGET_URL }} \
          -quickprogress -config api.key=${{ secrets.ZAP_API_KEY }} \
          -config context.file=/zap/wrk/juice-shop-context.json

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: /zap/ZAP_2.9.0/report_html.html
