name: OWASP ZAP Authenticated Scan - Juice Shop

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger
permissions:
  contents: read    
  issues: write    
  security-events: write  
  actions: read  

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Context File
        run: ls -lR .zap && cat .zap/juice-shop-context.json

      - name: Copy Context File to Working Directory
        run: cp .zap/juice-shop-context.json juice-shop-context.json

      - name: Run OWASP ZAP Full Scan with Authentication
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: ${{ secrets.ZAP_TARGET_URL }}
          fail_action: true
          cmd_options: >
            -config api.key=${{ secrets.ZAP_API_KEY }}
            -config context.file=/zap/wrk/juice-shop-context.json

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

