name: OWASP ZAP Authenticated Scan - Juice Shop

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger
permissions:
  contents: read    
  issues: write    
  security-events: write  
  actions: read  

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull OWASP ZAP Docker Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP Full Scan
        run: |
          docker run --rm \
            -v $(pwd):/zap/wrk:rw \
            --network=host \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t ${{ secrets.TARGET_URL }} \
            -J report_json.json \
            -w report_md.md \
            -r report_html.html \
            -config api.key=${{ secrets.ZAP_API_KEY }} \
            -config context.file=/zap/wrk/.zap/juice-shop-context.json

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            report_json.json
            report_md.md
            report_html.html
